import Head from 'next/head'

const About = () => {
    return ( 
        <div className="has-navbar-fixed-top">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=""> 
                <h1>About me</h1>
            </main>
        </div>
     );
}
 
export default About;