import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Header from '../components/Header'
import AvalabilityStatus from '../components/Home-components/Avalabitity-Satatus'
import Hero from '../components/Home-components/Hero'
import Testimonials from '../components/Home-components/Testimonials'
import Section from '../components/Section'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="has-navbar-fixed-top">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header>
          <Hero/>
        </Header>
        <Section>
          <Testimonials/>
        </Section>
        <Section divider={styles.sm_bottom_divider}>
          <AvalabilityStatus />
        </Section>
      </main>  
    </div>
  )
}
